app:
  environment: development

server:
  address: :8080

database:
  url: "postgres://user:password@localhost:5432/dbname" # Override with HEARTS_DATABASE_URL
  max_connections: 10
  min_connections: 2
  max_conn_lifetime: 1h

logger:
  level: debug
  mode: development

storage:
  endpoint: localhost:9000
  access_key_id: "CHANGE_ME" # Override with HEARTS_STORAGE_ACCESS_KEY_ID
  secret_access_key: "CHANGE_ME" # Override with HEARTS_STORAGE_SECRET_ACCESS_KEY
  use_ssl: false
  bucket_name: hearts-photos
  location: us-east-1
